name: Jellyfin

services:
  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION}
    container_name: jellyfin
    volumes:
      - /home/dhjensen/Videos:/media:ro
      - /etc/timezone:/etc/timezone:ro
      - jellyfin_config:/config:rw
      - jellyfin_cache:/cache:rw
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHEDSERVERURL}
    network_mode: host
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$

volumes:
  jellyfin_config:
  jellyfin_cache:
