name: Jellyfin

services:
  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION}
    container_name: jellyfin
    volumes:
      - ~/Videos:/media:rw
      - /etc/timezone:/etc/timezone:ro
      - jellyfin_config:/config:rw
      - jellyfin_cache:/cache:rw
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHEDSERVERURL}
    networks:
      - backend
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - traefik.enable=true

networks:
  backend:
    external: true
    driver: bridge

volumes:
  jellyfin_config:
  jellyfin_cache:
