name: Jellyfin

services:
  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION}
    container_name: jellyfin
    volumes:
      - ~/Videos:/media:rw
      - /etc/timezone:/etc/timezone:ro
      - jellyfin_config:/config:rw
      - jellyfin_cache:/cache:rw
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHEDSERVERURL}
    networks:
      - nginx-proxy-manager_frontend
      - backend
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - traefik.enable=true
      - traefik.http.routers.jellyfin-jellyfin.rule=Host(`jellyfin.dhjensen.tech`)
      - traefik.http.routers.jellyfin-jellyfin.middlewares=ipallowlocal@docker

networks:
  nginx-proxy-manager_frontend:
    driver: bridge
    external: true
  backend:
    external: true
    driver: bridge

volumes:
  jellyfin_config:
  jellyfin_cache:
